language: python

sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6-dev"

install:
  - pip install 'requests>=2.7'
  - pip install 'shapely>=1.5.13'
  - pip install coveralls

script:
  - nosetests -v --with-coverage --cover-package=pygbif

after_success:
  - coveralls --verbose
